### ISSUE TITLE
Why `Client` is not exported?

### ISSUE THREAD

**Issue by ZappaBoy** [alpacahq/typescript-sdk#2]
Why the `Client` type is not exported?

https://github.com/alpacahq/typescript-sdk/blob/84f5f9e8ffeb08f0b0d7d4de831399307f2a9773/factory/createClient.ts#L22-L28

Export the `Client` type can be useful to build functions that take in input an instance created with `createClient`.

**Comment by 117** [comment]
My bad, doing so now 😄.

**Comment by 117** [comment]
Resolved [3304134](https://github.com/alpacahq/typescript-sdk/commit/33041344d090619d3514b641af451d145894aee9), thanks for reporting!
